/**
 * Ducky AI | Coder — per-tool presentation metadata (icons + accent colors).
 * "Tool-owned UI presentation": every tool owns how
 * its calls render in the transcript instead of one generic wrench card.
 */

import {
  ArrowDownAZ,
  ArrowRightLeft,
  BarChart3,
  Bell,
  Binary,
  BookOpen,
  Bot,
  Braces,
  Brain,
  Calculator,
  Camera,
  Clock,
  Bookmark,
  CalendarClock,
  ClipboardCopy,
  ClipboardList,
  AppWindow,
  Copy,
  Crosshair,
  Dices,
  Download,
  Keyboard,
  Link2,
  Palette,
  Radar,
  Rss,
  ListOrdered,
  MousePointer2,
  MousePointerClick,
  FilePenLine,
  FilePlus2,
  FileText,
  Files,
  Fingerprint,
  FolderSearch,
  GitCompare,
  Globe,
  GraduationCap,
  Hash,
  HelpCircle,
  Info,
  ListPlus,
  ListTodo,
  ListTree,
  Monitor,
  NotebookPen,
  PanelTop,
  PenLine,
  PencilRuler,
  Plus,
  Regex,
  ScanEye,
  ScanText,
  ScrollText,
  Settings2,
  SlidersHorizontal,
  SquareTerminal,
  StickyNote,
  Table,
  Type,
  Users,
  TextSearch,
  Trash2,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

export interface ToolMeta {
  icon: LucideIcon;
  /** tailwind text color class for the icon */
  tint: string;
  /** tailwind border-left accent shown while running */
  accent: string;
  label: string;
}

const FALLBACK: ToolMeta = {
  icon: Wrench,
  tint: "text-muted-foreground",
  accent: "border-l-muted-foreground/40",
  label: "tool",
};

const REGISTRY: Record<string, ToolMeta> = {
  read_file: {
    icon: FileText,
    tint: "text-sky-400",
    accent: "border-l-sky-400/70",
    label: "read",
  },
  write_file: {
    icon: FilePlus2,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "write",
  },
  edit_file: {
    icon: FilePenLine,
    tint: "text-amber-400",
    accent: "border-l-amber-400/70",
    label: "edit",
  },
  glob: {
    icon: FolderSearch,
    tint: "text-violet-400",
    accent: "border-l-violet-400/70",
    label: "glob",
  },
  grep: {
    icon: ScanText,
    tint: "text-violet-400",
    accent: "border-l-violet-400/70",
    label: "grep",
  },
  bash: {
    icon: SquareTerminal,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "shell",
  },
  todo_write: {
    icon: ListTodo,
    tint: "text-teal-400",
    accent: "border-l-teal-400/70",
    label: "todos",
  },
  exit_plan_mode: {
    icon: ListTodo,
    tint: "text-teal-400",
    accent: "border-l-teal-400/70",
    label: "plan",
  },
  subagent: {
    icon: Bot,
    tint: "text-fuchsia-400",
    accent: "border-l-fuchsia-400/70",
    label: "delegate",
  },
  web_search: {
    icon: Globe,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "search",
  },
  web_fetch: {
    icon: Globe,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "fetch",
  },
  vision_describe: {
    icon: ScanEye,
    tint: "text-pink-400",
    accent: "border-l-pink-400/70",
    label: "vision",
  },
  ask_user_question: {
    icon: HelpCircle,
    tint: "text-orange-400",
    accent: "border-l-orange-400/70",
    label: "ask",
  },
  mcp_scan: {
    icon: Radar,
    tint: "text-fuchsia-400",
    accent: "border-l-fuchsia-400/70",
    label: "scan",
  },
  list_files: {
    icon: Files,
    tint: "text-sky-400",
    accent: "border-l-sky-400/70",
    label: "list",
  },
  file_info: {
    icon: Info,
    tint: "text-sky-400",
    accent: "border-l-sky-400/70",
    label: "info",
  },
  copy_file: {
    icon: Copy,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "copy",
  },
  move_file: {
    icon: ArrowRightLeft,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "move",
  },
  delete_file: {
    icon: Trash2,
    tint: "text-red-400",
    accent: "border-l-red-400/70",
    label: "delete",
  },
  append_file: {
    icon: ListPlus,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "append",
  },
  download_file: {
    icon: Download,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "download",
  },
  multi_edit: {
    icon: PencilRuler,
    tint: "text-amber-400",
    accent: "border-l-amber-400/70",
    label: "multi-edit",
  },
  create_files: {
    icon: FilePlus2,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "scaffold",
  },
  diff_files: {
    icon: GitCompare,
    tint: "text-amber-400",
    accent: "border-l-amber-400/70",
    label: "diff",
  },
  screen_capture: {
    icon: Camera,
    tint: "text-pink-400",
    accent: "border-l-pink-400/70",
    label: "screen",
  },
  browser_open: {
    icon: Globe,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "browse",
  },
  browser_snapshot: {
    icon: PanelTop,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "snapshot",
  },
  browser_tabs: {
    icon: ListTree,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "tabs",
  },
  browser_close: {
    icon: X,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "close-tab",
  },
  memory_save: {
    icon: Brain,
    tint: "text-fuchsia-400",
    accent: "border-l-fuchsia-400/70",
    label: "remember",
  },
  memory_list: {
    icon: Brain,
    tint: "text-fuchsia-400",
    accent: "border-l-fuchsia-400/70",
    label: "memories",
  },
  memory_forget: {
    icon: Brain,
    tint: "text-fuchsia-400",
    accent: "border-l-fuchsia-400/70",
    label: "forget",
  },
  note_write: {
    icon: NotebookPen,
    tint: "text-teal-400",
    accent: "border-l-teal-400/70",
    label: "note",
  },
  note_read: {
    icon: StickyNote,
    tint: "text-teal-400",
    accent: "border-l-teal-400/70",
    label: "read-note",
  },
  note_list: {
    icon: StickyNote,
    tint: "text-teal-400",
    accent: "border-l-teal-400/70",
    label: "notes",
  },
  session_stats: {
    icon: BarChart3,
    tint: "text-muted-foreground",
    accent: "border-l-muted-foreground/40",
    label: "stats",
  },
  session_export: {
    icon: ScrollText,
    tint: "text-muted-foreground",
    accent: "border-l-muted-foreground/40",
    label: "export",
  },
  calc: {
    icon: Calculator,
    tint: "text-lime-400",
    accent: "border-l-lime-400/70",
    label: "calc",
  },
  base64_encode: {
    icon: Binary,
    tint: "text-lime-400",
    accent: "border-l-lime-400/70",
    label: "b64",
  },
  base64_decode: {
    icon: Binary,
    tint: "text-lime-400",
    accent: "border-l-lime-400/70",
    label: "unb64",
  },
  sha256: {
    icon: Hash,
    tint: "text-lime-400",
    accent: "border-l-lime-400/70",
    label: "hash",
  },
  json_parse: {
    icon: Braces,
    tint: "text-lime-400",
    accent: "border-l-lime-400/70",
    label: "json",
  },
  json_query: {
    icon: Braces,
    tint: "text-lime-400",
    accent: "border-l-lime-400/70",
    label: "jq",
  },
  now: {
    icon: Clock,
    tint: "text-muted-foreground",
    accent: "border-l-muted-foreground/40",
    label: "now",
  },
  uuid: {
    icon: Fingerprint,
    tint: "text-violet-400",
    accent: "border-l-violet-400/70",
    label: "uuid",
  },
  random_token: {
    icon: Dices,
    tint: "text-violet-400",
    accent: "border-l-violet-400/70",
    label: "token",
  },
  clipboard_copy: {
    icon: ClipboardCopy,
    tint: "text-orange-400",
    accent: "border-l-orange-400/70",
    label: "copy-out",
  },
  clipboard_read: {
    icon: ClipboardList,
    tint: "text-orange-400",
    accent: "border-l-orange-400/70",
    label: "paste-in",
  },
  notify_user: {
    icon: Bell,
    tint: "text-orange-400",
    accent: "border-l-orange-400/70",
    label: "notify",
  },
  skill_list: {
    icon: GraduationCap,
    tint: "text-[#FF7A1A]",
    accent: "border-l-[#FF7A1A]/70",
    label: "skills",
  },
  skill_show: {
    icon: BookOpen,
    tint: "text-[#FF7A1A]",
    accent: "border-l-[#FF7A1A]/70",
    label: "skill",
  },
  get_config: {
    icon: Settings2,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "config",
  },
  set_config: {
    icon: SlidersHorizontal,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "tune",
  },
  session_list: {
    icon: Users,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "sessions",
  },
  session_new: {
    icon: Plus,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "new-session",
  },
  session_rename: {
    icon: PenLine,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "rename",
  },
  session_switch: {
    icon: Users,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "switch",
  },
  sort_lines: {
    icon: ArrowDownAZ,
    tint: "text-lime-400",
    accent: "border-l-lime-400/70",
    label: "sort",
  },
  dedupe_lines: {
    icon: ListOrdered,
    tint: "text-lime-400",
    accent: "border-l-lime-400/70",
    label: "dedupe",
  },
  count_words: {
    icon: Type,
    tint: "text-lime-400",
    accent: "border-l-lime-400/70",
    label: "count",
  },
  regex_edit: {
    icon: Regex,
    tint: "text-amber-400",
    accent: "border-l-amber-400/70",
    label: "regex",
  },
  workspace_stats: {
    icon: BarChart3,
    tint: "text-sky-400",
    accent: "border-l-sky-400/70",
    label: "overview",
  },
  preview_csv: {
    icon: Table,
    tint: "text-sky-400",
    accent: "border-l-sky-400/70",
    label: "csv",
  },
  pc_status: {
    icon: Monitor,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc",
  },
  pc_exec: {
    icon: SquareTerminal,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc-shell",
  },
  pc_read: {
    icon: FileText,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc-read",
  },
  pc_write: {
    icon: FilePlus2,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc-write",
  },
  pc_ls: {
    icon: FolderSearch,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc-ls",
  },
  pc_caps: {
    icon: Monitor,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc-caps",
  },
  pc_screen: {
    icon: Camera,
    tint: "text-pink-400",
    accent: "border-l-pink-400/70",
    label: "pc-screen",
  },
  pc_move: {
    icon: MousePointer2,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc-move",
  },
  pc_click: {
    icon: MousePointerClick,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc-click",
  },
  pc_type: {
    icon: Keyboard,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc-type",
  },
  pc_key: {
    icon: Keyboard,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "pc-key",
  },
  pc_announce: {
    icon: Crosshair,
    tint: "text-[#FF7A1A]",
    accent: "border-l-[#FF7A1A]/70",
    label: "here",
  },
  pc_windows: {
    icon: AppWindow,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "windows",
  },
  url_parse: {
    icon: Link2,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "url",
  },
  url_encode: {
    icon: Binary,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "encode",
  },
  url_decode: {
    icon: Binary,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "decode",
  },
  html_to_text: {
    icon: FileText,
    tint: "text-orange-400",
    accent: "border-l-orange-400/70",
    label: "html2text",
  },
  html_links: {
    icon: Link2,
    tint: "text-orange-400",
    accent: "border-l-orange-400/70",
    label: "links",
  },
  md_toc: {
    icon: ListTree,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "toc",
  },
  md_links: {
    icon: Link2,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "md-links",
  },
  color_convert: {
    icon: Palette,
    tint: "text-pink-400",
    accent: "border-l-pink-400/70",
    label: "color",
  },
  color_contrast: {
    icon: Palette,
    tint: "text-pink-400",
    accent: "border-l-pink-400/70",
    label: "contrast",
  },
  color_palette: {
    icon: Palette,
    tint: "text-pink-400",
    accent: "border-l-pink-400/70",
    label: "palette",
  },
  date_add: {
    icon: CalendarClock,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "date+",
  },
  date_diff: {
    icon: CalendarClock,
    tint: "text-slate-400",
    accent: "border-l-slate-400/70",
    label: "dateΔ",
  },
  rss_read: {
    icon: Rss,
    tint: "text-orange-400",
    accent: "border-l-orange-400/70",
    label: "rss",
  },
  snippet_save: {
    icon: StickyNote,
    tint: "text-teal-400",
    accent: "border-l-teal-400/70",
    label: "snippet",
  },
  snippet_get: {
    icon: StickyNote,
    tint: "text-teal-400",
    accent: "border-l-teal-400/70",
    label: "snippet",
  },
  snippet_list: {
    icon: StickyNote,
    tint: "text-teal-400",
    accent: "border-l-teal-400/70",
    label: "snippets",
  },
  snippet_delete: {
    icon: Trash2,
    tint: "text-red-400",
    accent: "border-l-red-400/70",
    label: "unsnip",
  },
  bookmark_save: {
    icon: Bookmark,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "bookmark",
  },
  bookmark_list: {
    icon: Bookmark,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "marks",
  },
  bookmark_open: {
    icon: Globe,
    tint: "text-cyan-400",
    accent: "border-l-cyan-400/70",
    label: "open-mark",
  },
  bookmark_delete: {
    icon: Trash2,
    tint: "text-red-400",
    accent: "border-l-red-400/70",
    label: "unmark",
  },
  disk_ls: {
    icon: Monitor,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "disk",
  },
  disk_read: {
    icon: FileText,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "disk-read",
  },
  disk_write: {
    icon: FilePlus2,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "disk-write",
  },
  disk_status: {
    icon: Monitor,
    tint: "text-emerald-400",
    accent: "border-l-emerald-400/70",
    label: "disk",
  },
};

/** `grep` vs `TextSearch`-style disambiguation for the second search tool */
REGISTRY["grep"] = {
  icon: TextSearch,
  tint: "text-violet-400",
  accent: "border-l-violet-400/70",
  label: "grep",
};

export function getToolMeta(name: string): ToolMeta {
  return REGISTRY[name] ?? FALLBACK;
}
